name = "Cliquing"
uuid = "570927c9-3032-54d7-b655-f6b1c77412c2"
version = "2.0.1"
author = "Invenia Technical Computing"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"

[compat]
Memento = "0.11, 0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
